task1
volodya0/csdt2223ki48yuziukvs28 pull request #1
Opened 2022-09-15 19:29 UTC by volodya0

2022-09-16 16:43 UTC, andrii-s-shpitser-lpnu-ua requested changes

2022-09-16 16:43 UTC, andrii-s-shpitser-lpnu-ua commented on README.md
> +Student: Volodymyr Yuziuk
do not use "." in tag name

2022-09-19 10:12 UTC, volodya0 commented on README.md
> +Student: Volodymyr Yuziuk
Tag name renamed.
I'm not sure if renaming is enough, maybe I need to create a new release, please let me know

2022-09-19 19:47 UTC, andrii-s-shpitser-lpnu-ua commented on README.md
> +Student: Volodymyr Yuziuk
![image](https://user-images.githubusercontent.com/78484371/191102869-fda90f3a-0f4c-4291-b722-976293c2ae77.png)

2022-09-19 19:47 UTC, andrii-s-shpitser-lpnu-ua commented on README.md
> +Student: Volodymyr Yuziuk
I still see dot

2022-09-20 19:20 UTC, volodya0 commented on README.md
> +Student: Volodymyr Yuziuk
Yes, strange, it loks like i can not rename the tag completely, now i see two different names (old and new) in different places. 
I will create new release

2022-09-20 19:57 UTC, andrii-s-shpitser-lpnu-ua approved these changes

2022-09-21 07:43 UTC, merged